### ISSUE TITLE
Symfony 4.4 support

### ISSUE THREAD

**Issue by cjprinse** [pug-php/pug-symfony#55]
Is it possible to add symfony 4.4 support again (as it was for the 2.8 release)?

**Comment by kylekatarnls** [comment]
The stream `^2` is dedicated to Symfony < 5
And the stream `^3` is dedicated to Symfony 5

If there is a bug in the package 2.8, I'll consider if it's worth to fix it and I'll release a 2.8.1 or a 2.9.0. Nothing prevent from publishing minor versions or patches (that's what semver is made for) except the balance between the effort cost and the benefit to support old versions.

But I won't mix with the streams, and if I drop Symfony < 5 to support the 5, it's because, there is a too big compatibility gap for the features used here.

Please explain your actual issue: why would you update to pug-symfony 3 but not to Symfony 5?

**Comment by cjprinse** [comment]
The issue i'm facing is that I want to cross mix twig and pug templates. I want the include a pug template in an existing twig template. I can't get it working in the 2.8 release. And I saw in the release notes this should be fixed in the 3.0 release.

**Comment by kylekatarnls** [comment]
Indeed, this is actually the new Symfony 5 features that allowed to include pug <-> twig files. Maybe it could be ported to pug-symfony 2 but I doubt it will be easy because of the lacking features of Symfony 4.

If a PR is proposed for that I could check it an merge it if nothing else would be broken. But the very recommended move is to upgrade to Symfony 5. I guess you will anyway soon or later do the upgrade.

Let me know if there is something else you think I should take into consideration.

**Comment by cjprinse** [comment]
Which 5.0 features are relevant for this then? I believe the 5.0 does not included any new features since 4.4.

https://symfony.com/doc/current/contributing/community/releases.html#backward-compatibility

> Both versions have the same new features, but they differ in the deprecated features. The oldest version (3.4 in this example) contains all the deprecated features whereas the new version (4.0 in this example) removes all of them.
